"""Add complaint attachment

Revision ID: 8489c11e7bd4
Revises: fe48d1b68986
Create Date: 2026-07-02 10:53:00.123068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8489c11e7bd4'
down_revision = 'fe48d1b68986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
